version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: org.jetbrains.intellij
    versions:
    - 0.6.5
    - 0.7.0
    - 0.7.1
    - 0.7.2
  - dependency-name: org.openapitools:openapi-generator
    versions:
    - 5.0.0
    - 5.0.1
  - dependency-name: org.openapitools:openapi-generator-cli
    versions:
    - 5.0.0
    - 5.0.1
  - dependency-name: org.threeten:threetenbp
    versions:
    - 1.5.0
  - dependency-name: junit:junit
    versions:
    - 4.13.1
